version: 2.1

# orbs - reusable packages for use
# NOTE: tab is important in .yml config file
orbs: 
  node: circleci/node@5.0.1 # Security vulnerability: Outdated node current is 5.2.0
  docker: circleci/docker@2.1.4
  # heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0 #compare the node and docker orbs, the snyk orb starts with snyk and it is considered the third party orb

#Try out: Assignment 4.5
# executors: 
#   docker-publisher:
#     environment: 
#       IMAGE_TAG: ylongtay/education-space:v2
#     docker:
#       - image: docker:publish
#Try out: Assignment 4.5

# jobs - set of instructions / functions
jobs:
  build: # job name
    docker: # environment
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : |
          echo "Running tests..."
          npm run test

  #Try out: Assignment 4.5
  # build-and-push:
  #   build:
  #     executor: docker-publisher
  #     steps:
  #       - checkout
  #       - setup_remote_docker
  #       - run: |
  #           echo "Building Docker image..."
  #           docker build --t "${IMAGE_TAG}" .
  #       - run: |
  #           echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_LOGIN}" --password-stdin
  #           docker push "${IMAGE_TAG}"
  #Try out: Assignment 4.5

  publish: #also known as the build-and-push
    executor: docker/docker # executor define the execution environment in which the steps of a job will run.
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: ylongtay/education-space
          # Mini activity 3 - add a tag called v1.0.1 and push the tag in docker hub
          tag: v1.0.1
      - docker/push: #pushes the image to the specified account in the environment variables
          image: ylongtay/education-space
          tag: v1.0.1

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a  yonglong-ntusctp-devops
            heroku container:release web -a yonglong-ntusctp-devops
  
  Scan:
    docker:
      - image: cimg/node:16.10
    environment: #the environment allows us to create an environment for the job and allows us to create custom environment variables
      IMAGE_NAME: ylongtay/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME . #$IMAGE_NAME gets the value from the env we created above
      - snyk/scan:
          docker-image-name: $IMAGE_NAME



# workflow - defines what sequence will the jobs run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build:
          filters: # added for assignment 4.6
            branches:
              only: main #the build job would only run when code changes are pushed to the main (4.7)
      - test:
          requires:
            - build # Added so that build is done before test
          filters: # added for assignment 4.6
            branches:
              only:
                - main
      - scan: #the scan job added to workflow (4.7)
          requires:
            - build
          filters:
            branches:
              only: main
      #Mini activity #2 - how to make the publish job execute after the test job?
      # - publish:
      #     requires:
      #       - test
      # - deploy:
      #     requires:
      #       - publish
# If commit and push circleci testing will fail - req Docker environment setup
# Above 7 lines commented out for lesson-4.7